version: '3'

services:
    web-picture:
        build: ./.build-picture
        image: vonkrafft/picture
        container_name: web-picture
        user: app
        volumes:
            - ./picture/app:/usr/src/app:ro
            - ./picture/data:/usr/src/data
            - ./picture/media:/usr/src/media
            - ./picture/trash:/usr/src/trash
        ports:
            - 127.0.0.1:80:8080
        environment:
            PICTURE_TOKEN: my_awesome_token
        command: [ "python", "/usr/src/app/picture.py" ]

